<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>bms_editer.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" Version="12.0.5" />
    <PackageReference Include="Avalonia.Skia" Version="12.0.5" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.3" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\muse dash bms editer\muse dash bms editer.csproj" />
  </ItemGroup>

</Project>
